before_script:
  - apt-get update
  - apt-get install python3.6
  - apt-get install python3-pip python3-dev
  - python3 --version

stages:
  - test

test:
  stage: test
  script:
  - pip3 install -r requirements.txt
  - python3 test/run_tests.py
